# Generated by Django 3.2.7 on 2021-12-23 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211215_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bboard',
            name='content',
            field=models.TextField(blank=True, help_text='Напишите об автомобиле', null=True, verbose_name='Описание авто'),
        ),
        migrations.AlterField(
            model_name='bboard',
            name='title',
            field=models.CharField(error_messages={'invalid': 'Неправильное название'}, max_length=50, validators=[django.core.validators.RegexValidator(regex='^.{4,}$')], verbose_name='Модель автомобиля'),
        ),
    ]
